---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "enter vcenter name here"
    vcenter_user: "enter vcenter user"
    vcenter_pass: "enter vcenter pass"
    datacenter_name: "you get the idea"
    resource_pool: "same same same"
    vcenter_cluster: "figure out why not working"
    vcenter_folder: "same same same"
  tasks:
  - name: Create a VM folder on given datacenter
  community.vmware.vcenter_folder:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter_name: "{{ datacenter_name }}"
    folder_name: ACMOCP
    folder_type: vm
    state: present
  register: vm_folder_creation_result
  delegate_to: localhost

  - name: Create Bootstrap VM
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      datacenter: "{{ datacenter_name }}"
      cluster: [insert your cluster name here]
      resource_pool: [insert your RP name here]
      folder: /{{ datacenter_name }}/vm/[insert your folder name here]
      name: [insert your BootStrap VM name here]
      state: poweredon
      guest_id: rhel8_64Guest
      disk:
      - size_gb: 120
        type: thin
        datastore: SATA-SAN
      hardware:
        version: 15
        boot_firmware: BIOS
        memory_mb: 16384
        num_cpus: 4
        scsi: paravirtual
      networks:
      - name: 172ocp
        mac: 00:50:56:a1:60:22
        ip: 172.16.20.109
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: false
    delegate_to: localhost
    register: deploy_vm

  - name: Create Master VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      datacenter: "{{ datacenter_name }}"
      cluster: HomeLab
      resource_pool: "{{ resource_pool }}"
      folder: /{{ datacenter_name }}/vm/{{ vcenter_folder }}
      name: "{{ item.name }}"
      state: poweredon
      guest_id: rhel8_64Guest
      disk:
      - size_gb: 120
        type: thin
        datastore: SSD-SAN
      hardware:
        version: 15
        boot_firmware: BIOS
        memory_mb: 24576
        num_cpus: 4
        scsi: paravirtual
      networks:
      - name: 172ocp
        mac: "{{ item.mac }}"
        ip: "{{ item.ip }}"
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: false
    delegate_to: localhost
    register: deploy_vm
    loop:
      - { name: 'ACMmaster0', mac: '00:50:56:a1:79:d9', ip: '172.16.20.103' }
      - { name: 'ACMmaster1', mac: '00:50:56:a1:5c:08', ip: '172.16.20.104' }
      - { name: 'ACMmaster2', mac: '00:50:56:a1:04:c5', ip: '172.16.20.105' }

  - name: Create Worker VMs
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: false
      datacenter: "{{ datacenter_name }}"
      cluster: HomeLab
      resource_pool: KVOCP
      folder: /{{ datacenter_name }}/vm/{{ vcenter_folder }}
      name: "{{ item.name }}"
      state: poweredon
      guest_id: rhel8_64Guest
      disk:
      - size_gb: 120
        type: thin
        datastore: SSD-SAN
      hardware:
        version: 15
        boot_firmware: BIOS
        memory_mb: 98304
        num_cpus: 16
        scsi: paravirtual
      networks:
      - name: 172ocp
        mac: "{{ item.mac }}"
        ip: "{{ item.ip }}"
        netmask: 255.255.255.0
        device_type: vmxnet3
      - name: 172ocp
        connected: no
        start_connected: no
        device_type: vmxnet3
      wait_for_ip_address: false
    delegate_to: localhost
    register: deploy_vm
    loop:
      - { name: 'KVworker0', mac: '00:50:56:a1:9b:b2', ip: '172.16.20.104' }
      - { name: 'KVworker1', mac: '00:50:56:a1:4f:d3', ip: '172.16.20.105' }
      - { name: 'KVworker2', mac: '00:50:56:a1:27:29', ip: '172.16.20.106' }
