apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 100Gi
  nfs:
    path: /mnt/SATA/ocpsata
    server: 192.168.1.213
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
