apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
      storage: 200Gi
  nfs:
    path: /your/path/here
    server: 0.0.0.0
  persistentVolumeReclaimPolicy: Retain
